

### Crear respaldo
POST http://apirespaldo.us-east-1.elasticbeanstalk.com/respaldos
Content-Type: application/json

{
	"tipo": "Basico",
	"descripcion": "Respaldo inicial"
}

### Listar respaldos
GET http://apirespaldo.us-east-1.elasticbeanstalk.com/respaldos

### Obtener respaldo por ID
GET http://localhost:5000/respaldos/1

### Restaurar respaldo
POST http://localhost:5000/respaldos/restaurar
Content-Type: application/json

{
	"idRespaldo": 1
}
