### Listar todos los pedidos
GET http://pedido.us-east-1.elasticbeanstalk.com/
Accept: application/json

### Obtener pedido por id
GET http://pedido.us-east-1.elasticbeanstalk.com/
Accept: application/json

### Crear pedido
POST http://pedido.us-east-1.elasticbeanstalk.com/
Content-Type: application/json

{
	"cliente": "Juan Perez",
	"estado": "PENDIENTE",
	"tienda": "Sucursal Centro"
}

### Actualizar pedido
PUT http://pedido.us-east-1.elasticbeanstalk.com/
Content-Type: application/json

{
	"id_pedido": 1,
	"cliente": "Juan Perez",
	"estado": "EN_PROCESO",
	"tienda": "Sucursal Centro"
}

### Eliminar pedido
DELETE http://pedido.us-east-1.elasticbeanstalk.com/
Accept: application/json
