### Listar todas las tiendas
GET http://tienda.us-east-1.elasticbeanstalk.com/
Accept: application/json

### Obtener tienda por id
GET http://tienda.us-east-1.elasticbeanstalk.com/
Accept: application/json

### Crear tienda
POST http://tienda.us-east-1.elasticbeanstalk.com/
Content-Type: application/json

{
    "horarioApertura": "08:00-18:00",
    "personalAsignado": "Equipo A",
    "politicasLocales": "Uso obligatorio de bolsas reciclables"
}

### Actualizar tienda
PUT http://tienda.us-east-1.elasticbeanstalk.com/
Content-Type: application/json

{
    "id": 1,
    "horarioApertura": "09:00-19:00",
    "personalAsignado": "Equipo B",
    "politicasLocales": "Promoción de productos locales"
}

### Eliminar tienda
DELETE http://tienda.us-east-1.elasticbeanstalk.com/
Accept: application/json