### Listar todas las tiendas
GET http://localhost:1000/tiendas
Accept: application/json

### Obtener tienda por id
GET http://localhost:1000/tiendas/1
Accept: application/json

### Crear tienda
POST http://localhost:1000/tiendas
Content-Type: application/json

{
	"horarioApertura": "08:00-18:00",
	"personalAsignado": "Equipo A",
	"politicasLocales": "Uso obligatorio de bolsas reciclables"
}

### Actualizar tienda
PUT http://localhost:1000/tiendas
Content-Type: application/json

{
	"idTienda": 1,
	"horarioApertura": "09:00-19:00",
	"personalAsignado": "Equipo B",
	"politicasLocales": "Promoción de productos locales"
}

### Eliminar tienda
DELETE http://localhost:1000/tiendas/1
Accept: application/json
