@baseUrl = http://localhost:8080

### Listar envios
GET {{baseUrl}}/envio

### Obtener envio por id
GET {{baseUrl}}/envio/1

### Crear envio
POST {{baseUrl}}/envio
Content-Type: application/json

{
	"cliente": "Juan Perez",
	"destino": "Sucursal Centro",
	"direccionEntrega": "Av. Principal 123",
	"idTienda": 10,
	"costo": 25.5,
	"fechaEstimadaEntrega": "2025-12-31"
}

### Actualizar envio
PUT {{baseUrl}}/envio
Content-Type: application/json

{
	"idEnvio": 1,
	"estado": "EN_RUTA",
	"destino": "Sucursal Norte",
	"direccionEntrega": "Calle 8 #99",
	"idTienda": 11,
	"costo": 27.0,
	"fechaEstimadaEntrega": "2026-01-05"
}

### Eliminar envio
DELETE {{baseUrl}}/envio/1
