### Listar inventarios
GET http://ecomarket-inventario.us-east-1.elasticbeanstalk.com/
Accept: application/json

### Obtener inventario por id
GET http://ecomarket-inventario.us-east-1.elasticbeanstalk.com/
Accept: application/json

### Crear inventario
POST http://ecomarket-inventario.us-east-1.elasticbeanstalk.com/
Content-Type: application/json

{
    "nombreProducto": "Producto A",
    "cantidadStock": 100,
    "precio": 50.0,
    "categoria": "Electrónica"
}

### Actualizar inventario
PUT http://ecomarket-inventario.us-east-1.elasticbeanstalk.com/
Content-Type: application/json

{
    "id": 1,
    "nombreProducto": "Producto A Actualizado",
    "cantidadStock": 150,
    "precio": 55.0,
    "categoria": "Electrónica"
}

### Eliminar inventario
DELETE http://ecomarket-inventario.us-east-1.elasticbeanstalk.com/
Accept: application/json